sudo: false
language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
env:
- secure: iAV87u4/ZASPv8Un8YCBKvhlIoc77lu8qwNJZ1Xh2alYx/yA7Wh/ANFPWGXvCGMUmxBi/bxMzy+P+/gIt5I4f7YNWyB16g/VGkNtKB/jlfC0Y1UC1NAW+HtF8v7c2U81ASyQyQ+uSgf3YJcsY3G+f0gAVdaDv+GjSxrQb0aUMRIgxpB/pZQywsIDyTLxkENLQ3GawyZAlH98b95rNgokJfeImeuoqteFg8ArK09DzXmVbyZrVlbGzjlhLEgzFBsFBI08mRclHK9z/KGZ0/8oZeV5jtQnCLUKP5Cxhcl2mMOmVCAHdxqTa/kg4irUmmxIOCWmWDhHxOg6wcMwRNNhZryj6NGekdVdVoUhXuCOmxfTlq0i66XXjD7GTNRqv6K9ri9mVEEfKhDcANWiHBUwtJzNOcZ+5ESWkxtXCkV9JSY+j8P7bUoZPvZhDmI+ypnVDuKr5KoIju3Jq60y7bCTyKIybOapHKEpjumcJYD5/Yup0qN4/mNWKgQwH/zp1tnYS0ExOYUgamcoJoIc1UifHuIB+XmEQHNRQTpNmY9UwkVtGKvdrIoM8Gx6xyQZxvGU3zhzfRorhQmgnMhNDTR+tHQlHXrP4JQtiKQgjgrJWAhmh7WuBqkSjpO3lQ9ZKd3f2Ygde6RjACl5wRTkbnAiZPtkAU0h3v9ew79fEFD2aTA=
after_success:
- ./scripts/trigger-dependent-build.sh
notifications:
  slack:
    room:
      secure: K9zW7PwBL0NW64rc0VPB28KjAEExi2LCfVb1J0VcIMXovd7jAvk7W4imscLzw3yUJ0eMZ1HqLPLzQgcu3sAb6ESie6m5rxbqDR7Ma0n5TzACeQzTn/o95gQQIopg36bpEvfCiCDmID0/ThmiO3SIwGbd4cu7vfFkDzam6lkJ1XaCAeYM57yaUxZ+JxlziDQ17epBmlA2rdKUH7oVkROGq2Fgde1um6J/Tb3Jr547bRkA3lujQYzv/X38Nr/pLjUe4eg/8W+y5rESPl/lfOaeVbZx78h3zNNO1V48365HZevk2S2fE4/4cxr8rfKuzOdGYjrr6XenfLbNyB2X2VLDMPquPqOTKmTQglspb2KIiUa8bXfEtdraFNQU+hIpX54cwyHfqz5E/MXPO6yE3X0gBcEp8a4H8ITudS9XIIQZ33o8BFvBf8dDzbQARjzKOoZvdgsPPezp1zj+8p7NvMMz9t/ivVTHH9XHGhmUGV4HTtUHBQqbdlIuXR22t4dOlOWQdlkXeNc3/tMOEQGYHb54uFUjVc6ianvxydV5ZyafVW2Q36MFO3Gqyc+8b79Ha3MgzSoLwUdDyYcxJsnzh4vMHVURmdKHWRaF2LHHlIMb6bENAP379JUS08H77HJLgm9fP/MYkqahGW5AY6zrcsvrEVBCZm5SMEXqzxZ6sRgkRD8=
