sudo: false
language: python
python:
- '3.4'

install:
- pip install -r requirements_for_test.txt

script:
- ./scripts/run_tests.sh

after_success:
     - secure: "iAV87u4/ZASPv8Un8YCBKvhlIoc77lu8qwNJZ1Xh2alYx/yA7Wh/ANFPWGXvCGMUmxBi/bxMzy+P+/gIt5I4f7YNWyB16g/VGkNtKB/jlfC0Y1UC1NAW+HtF8v7c2U81ASyQyQ+uSgf3YJcsY3G+f0gAVdaDv+GjSxrQb0aUMRIgxpB/pZQywsIDyTLxkENLQ3GawyZAlH98b95rNgokJfeImeuoqteFg8ArK09DzXmVbyZrVlbGzjlhLEgzFBsFBI08mRclHK9z/KGZ0/8oZeV5jtQnCLUKP5Cxhcl2mMOmVCAHdxqTa/kg4irUmmxIOCWmWDhHxOg6wcMwRNNhZryj6NGekdVdVoUhXuCOmxfTlq0i66XXjD7GTNRqv6K9ri9mVEEfKhDcANWiHBUwtJzNOcZ+5ESWkxtXCkV9JSY+j8P7bUoZPvZhDmI+ypnVDuKr5KoIju3Jq60y7bCTyKIybOapHKEpjumcJYD5/Yup0qN4/mNWKgQwH/zp1tnYS0ExOYUgamcoJoIc1UifHuIB+XmEQHNRQTpNmY9UwkVtGKvdrIoM8Gx6xyQZxvGU3zhzfRorhQmgnMhNDTR+tHQlHXrP4JQtiKQgjgrJWAhmh7WuBqkSjpO3lQ9ZKd3f2Ygde6RjACl5wRTkbnAiZPtkAU0h3v9ew79fEFD2aTA="
     - ./scripts/trigger-dependent-build.sh


notifications:
  slack:
    rooms:
      secure: MMDS75tBOitrK4FXShmUjRB687GtCnVKvq0640Q4pWXaqBVVojQ2p9GlYYpFHxTmG7DhvPBjlq6MaTH41mwJwjO3y7cH2iWL69KbFX2PvjOk+zwIzdzIi29uhs9aOhhILvomT0HY2PPjLnHkrcrBszYG7LYvac+eqnzAdOlzSAozazfAGI1IUF3UdcZX4awLgv027WnxC2CXm/ZY7l1xsLwxtACKIC0CS2fB0fgK7BJfFOKTjvj60gKx15ffR2gRVMNklYaW2VuaATT/VMeLJjYVoWeHkOIqW5yqKBelWQfWXIivmDfhL0zPk69sm51w3sQkzJxsr67rzjdpUx8WqFtin/CCIHwDJluOmIRD8rWZSgQf5LQUPy+gsUvSyoeebuh/hA7I8x7hYvmiptCVDi8mBjVFxfSSODQscJii61QDraOCrJYqWWabHPY4TeqHw7HqAgHBidHquowsZWuxyfhCMaRQLS72HTWKWNkK44+y8v1E+TomYmTvFg4ZSLFkievmhxsR5FUewbXjQ64zKw3oBT56H2queCLJ7MiLZNvza239T4/lqPIcF7YrOhrce3ozONviWtoYldq9NNPQSkObw0NdTi7PkY4xF2Nw6MaDWuIAhmkRIJNC3JdadkJ8ZdzztRdYhUjp/6L42oLaOcsJdE99URUhtj9GWaLGyK0=
