sudo: false
language: python
python:
- '3.4'

install:
- pip install -r requirements_for_test.txt

script:
- ./scripts/run_tests.sh

after_success:
     auth_token:
        secure: "mKGIWzWjuIlXgLnY4JLEjgvOi5+W/ynuQ7hbRjFWuitfb4xtYOS4dYbn28z8ijiR/bd8kvoigs1j2q2HvAr6W+N0wdBS0FJPX8HxKVOvdq3sdMZzi5ilq0dJNymGAOwP8fy8mNYdo7r4jjoGtV+Y5oWlFI4XwsI4zvkRaaSXMqfkOrBSW5BCwI7LmTgwhhIGqhc9EluU0DuNoq8bngB8Em8tlvMnSZooAbz6kSC5gfLOEX2/8C6uVPoD56E1deZj7xUhjjrMCTevlfviM67GMdm/+uwbJRvU2b20JkBlDUHM5C3WXin6Nwud4gjf2nL95qhrCUSLft7C4zMk76cuELxXIQlxHcgl2oYtMRvI/6fesewmf3R23VVLES/9vrh1kAxue7V1NUmmpw33y6i8VQGTM7gvQSIa83WymQf8Hjctak5j1YA1liIvTGE+psAh8RSkwqXiGKb1CD4TGvel2/4I+8qpzUeko91QVAZboG2dlw8w31Vfb93M9pZfFn7orZkJ+P+7YNPhi/UM5FleO2DH5kjf2lP1biL+5aPsXOMa5/O+OPghngEPFopzYiwCGqjHZlRIPZ0fDKbnFcDdObVyYQZTV0nccru/MguCqChLR2IGQPBP7OSrz4dEL+9NQ3x7SKz4K9wR1o6yjbCTDGnQtiWKLeP/dTmg/h+JQZk="
     - ./scripts/trigger-dependent-build.sh


notifications:
  slack:
    rooms:
      secure: MMDS75tBOitrK4FXShmUjRB687GtCnVKvq0640Q4pWXaqBVVojQ2p9GlYYpFHxTmG7DhvPBjlq6MaTH41mwJwjO3y7cH2iWL69KbFX2PvjOk+zwIzdzIi29uhs9aOhhILvomT0HY2PPjLnHkrcrBszYG7LYvac+eqnzAdOlzSAozazfAGI1IUF3UdcZX4awLgv027WnxC2CXm/ZY7l1xsLwxtACKIC0CS2fB0fgK7BJfFOKTjvj60gKx15ffR2gRVMNklYaW2VuaATT/VMeLJjYVoWeHkOIqW5yqKBelWQfWXIivmDfhL0zPk69sm51w3sQkzJxsr67rzjdpUx8WqFtin/CCIHwDJluOmIRD8rWZSgQf5LQUPy+gsUvSyoeebuh/hA7I8x7hYvmiptCVDi8mBjVFxfSSODQscJii61QDraOCrJYqWWabHPY4TeqHw7HqAgHBidHquowsZWuxyfhCMaRQLS72HTWKWNkK44+y8v1E+TomYmTvFg4ZSLFkievmhxsR5FUewbXjQ64zKw3oBT56H2queCLJ7MiLZNvza239T4/lqPIcF7YrOhrce3ozONviWtoYldq9NNPQSkObw0NdTi7PkY4xF2Nw6MaDWuIAhmkRIJNC3JdadkJ8ZdzztRdYhUjp/6L42oLaOcsJdE99URUhtj9GWaLGyK0=
