sudo: false
language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
env:
- secure: iAV87u4/ZASPv8Un8YCBKvhlIoc77lu8qwNJZ1Xh2alYx/yA7Wh/ANFPWGXvCGMUmxBi/bxMzy+P+/gIt5I4f7YNWyB16g/VGkNtKB/jlfC0Y1UC1NAW+HtF8v7c2U81ASyQyQ+uSgf3YJcsY3G+f0gAVdaDv+GjSxrQb0aUMRIgxpB/pZQywsIDyTLxkENLQ3GawyZAlH98b95rNgokJfeImeuoqteFg8ArK09DzXmVbyZrVlbGzjlhLEgzFBsFBI08mRclHK9z/KGZ0/8oZeV5jtQnCLUKP5Cxhcl2mMOmVCAHdxqTa/kg4irUmmxIOCWmWDhHxOg6wcMwRNNhZryj6NGekdVdVoUhXuCOmxfTlq0i66XXjD7GTNRqv6K9ri9mVEEfKhDcANWiHBUwtJzNOcZ+5ESWkxtXCkV9JSY+j8P7bUoZPvZhDmI+ypnVDuKr5KoIju3Jq60y7bCTyKIybOapHKEpjumcJYD5/Yup0qN4/mNWKgQwH/zp1tnYS0ExOYUgamcoJoIc1UifHuIB+XmEQHNRQTpNmY9UwkVtGKvdrIoM8Gx6xyQZxvGU3zhzfRorhQmgnMhNDTR+tHQlHXrP4JQtiKQgjgrJWAhmh7WuBqkSjpO3lQ9ZKd3f2Ygde6RjACl5wRTkbnAiZPtkAU0h3v9ew79fEFD2aTA=
after_success:
- ./scripts/trigger-dependent-build.sh
notifications:
  slack:
    secure: cCo/V9JFPr24uefRlaVuGzT1M+JHNJA6iLNqGk5HjTHI59x/oh3dFqb+Sxy6WJYH41uUOr2cVaj/hQWDh1oLYjngIsARtBaawO7ptb93t3AE+ZZ3x3Y8H0o0776KeJn30ZuhTdyf3xQqoZKqZFq47ZJDZM8a/q4YgA0BWCbewOZInfVAd+J2ZzlG02QZ4dY0VyJO8RcaczCf57WKwpznCV+0erXzETOqiLxkw8BPCVU6tJ3pCQKAU6j1KUQv+svSHt1UH3VUGmq426TX4m+vtPPObkPk62rNxFvgSOxNroBq/EtKpQ95Dk7aaXMns9VY1uej4rQuBwSx9uKrdogvIFgG8FqoYg64QYl1jdOCyLjHMcAdINNourlqr4PDOUucSy+bkh8HhW8WVHp99lLb4VqrqtlhB879TVIKaZaSc5TIkMbKWGjl1iwb+cmYJ6oLfV16JpxwJyU9lq3SZlmFylBgnwYWpjQjI0GmT2+sA9diVL34B15pEMwlgvS+0AgbMN8hLTI2eqXapcSG0qCjLkkbVV45cDKGub1jhSAWFw11D6VYDD5t8ZTwGDHCMR2aCE+g0pbbPhMInEelI22jUaJRAMoyOvipMvmMCwK+OY8revNeuGx+Xa3XKI9LZGFkrBeDs6kKUw0xH5x4Wd2VZjHP387Bta4OGEZOgAkLw0I=
